name: Deploy to firebase

on:
  pull_request_review:
    types: [ submitted ]
  push:
    branches: [ master, develop ]

jobs:
  deploy:
    # if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - uses: actions/checkout@develop
      - uses: borales/actions-yarn@v2.3.0
        with:
          path: ./front
          cmd: install
      - uses: mohammed-atif/firebase-publish-react@v1.0
        with:
          path: ./front
          firebase-token: ${{ secrets.FIREBASE_TOKEN }}