name: Deploy to firebase

on:
  pull_request_review:
    types: [ submitted ]
  push:
    branches: [ master, develop ]

defaults:
  run:
    working-directory: ./front

jobs:
  deploy:
    # if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: mohammed-atif/firebase-publish-react@v1.0
        with:
          firebase-token: ${{ secrets.FIREBASE_TOKEN }}